### ISSUE TITLE
NSFW sticker packs not supported

### ISSUE THREAD

**Issue by RaiJoh** [FHPythonUtils/SigStickers#2]
Hi,

the tool works fine with urls like: https://signal.art/addstickers/#pack_id=...&pack_key=...
but not with NSFW packs like: https://signalstickers.com/pack/9de0f4c3a87b3c897ec0307786e1e56a
No exception is thrown and the program terminates with no result.
Could you support this too please?

Thanks a lot!
RaiJoh

**Comment by FredHappyface** [comment]
Please click on 'Add to Signal' to reveal the sharing url

![image](https://user-images.githubusercontent.com/41634689/150677601-84d02554-445a-4ab3-bd5a-f117d9df6348.png)


https://signal.art/addstickers/#pack_id=9de0f4c3a87b3c897ec0307786e1e56a&pack_key=4252d243cce5dc39fe1aa3130a7118e1f88da4a57804d3e6f253aeb9a3f8fd97

Then enter that url into sigstickers to download the pack. Hope this helps :)

**Comment by RaiJoh** [comment]
Great! Thank you very much!
