### ISSUE TITLE
Can't download packs with ":" (Colon) in it

### ISSUE THREAD

**Issue by MicroHazard** [FHPythonUtils/SigStickers#3]
I'm trying to download this pack https://www.sigstick.com/pack/uWsRnOqK7EzDjspnZ5Ct
But because the pack name has a colon, and you can't name files/folders with colons in it, it fails to create the folder
![image](https://github.com/FHPythonUtils/SigStickers/assets/83976301/251d50b9-e53f-4630-9592-fde741c91c00)

**Comment by FredHappyface** [comment]
Thanks for this. I'll update the logic!

**Comment by FredHappyface** [comment]
Fixed in https://github.com/FHPythonUtils/SigStickers/releases/tag/2024.1
